(()=>{
  const STORAGE_KEY='cpl-fleet-preview-functional-v5',base=window.FLEET_PREVIEW_DATA,$=id=>document.getElementById(id);
  const machineKinds=new Set(['Retroescavadeira','Escavadeira']),fmt=value=>Number(value||0).toLocaleString('pt-BR',{maximumFractionDigits:2}),parse=value=>Number(String(value||'').replace(/[.,]/g,''))||0;
  const planKey=row=>`${row.code}|${row.description}`;
  function initialPlanState(item,currentReading){const result={};item.plan.filter(row=>!row.group).forEach((row,index)=>{const values=item.unit==='h'?[250,500,1000,2000]:[5000,10000,15000,20000],interval=values[index%values.length],factor=index===0?1.2:index===6?.9:.3+(index%4)*.08;result[planKey(row)]={interval,lastReading:Math.max(0,Math.round(currentReading-interval*factor)),lastDate:''};});return result;}
  function createState(){return{lastImportAt:null,alertSettings:{collaborator:'Responsável pela frota',hoursThreshold:50,kmThreshold:5000},lessors:[],equipment:JSON.parse(JSON.stringify(base.equipment)).map(item=>{const unit=machineKinds.has(item.kind)?'h':'km',currentReading=unit==='h'?parse(item.readings.hours):parse(item.readings.km),prepared={...item,unit,currentReading,ownership:'owned',historyRecords:[]};prepared.planState=initialPlanState(prepared,currentReading);return prepared;})};}
  function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved?.equipment?.length)return saved;}catch{}const state=createState();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return state;}
  let state=loadState(),selected=null,pendingReading=null;
  const form=$('driverReadingForm'),dialog=$('confirmDialog'),equipment=[...state.equipment].sort((a,b)=>a.identifier.localeCompare(b.identifier));
  $('vehicleSelect').innerHTML=equipment.map(item=>`<option value="${item.id}">${item.identifier} · ${item.unit==='h'?'HORAS':'KM'}</option>`).join('');
  const requested=new URLSearchParams(location.search).get('equipamento'),requestedItem=equipment.find(item=>item.identifier===requested);if(requestedItem)$('vehicleSelect').value=requestedItem.id;
  function renderVehicle(){selected=equipment.find(item=>item.id===$('vehicleSelect').value)||equipment[0];const hours=selected.unit==='h',unit=hours?'hrs':'km';$('vehicleSelect').value=selected.id;$('vehicleIdentifier').textContent=selected.identifier;$('identifierLabel').textContent=hours?'IDENTIFICAÇÃO DA MÁQUINA':'PLACA DO VEÍCULO';$('pageReadingTitle').textContent=hours?'Atualize as horas':'Atualize o KM';$('previousReadingLabel').textContent=hours?'HORAS ANTERIORES':'KM ANTERIOR';$('updatedReadingLabel').textContent=hours?'Horas atualizadas':'KM atualizado';$('currentReading').textContent=`${fmt(selected.currentReading)} ${unit}`;$('readingUnit').textContent=unit;$('reviewReadingBtn').textContent=hours?'Revisar horas':'Revisar KM';form.elements.reading.value='';$('readingFeedback').className='feedback';$('readingFeedback').textContent=hours?'As horas atualizadas não podem ser menores que as anteriores.':'O KM atualizado não pode ser menor que o anterior.';}
  function validateReading(){const raw=form.elements.reading.value,value=Number(raw),feedback=$('readingFeedback'),hours=selected.unit==='h',unit=hours?'hrs':'km';if(raw===''){feedback.className='feedback';feedback.textContent=hours?'Informe as horas mostradas no painel.':'Informe o KM mostrado no painel.';return false;}if(value<selected.currentReading){feedback.className='feedback error';feedback.textContent=`Valor inválido: a leitura anterior é ${fmt(selected.currentReading)} ${unit}.`;return false;}feedback.className='feedback ok';feedback.textContent=`Diferença de ${fmt(value-selected.currentReading)} ${unit}.`;return true;}
  $('vehicleSelect').onchange=renderVehicle;form.elements.reading.oninput=validateReading;
  form.onsubmit=event=>{event.preventDefault();if(!validateReading())return;pendingReading=Number(form.elements.reading.value);const difference=pendingReading-selected.currentReading,hours=selected.unit==='h',unit=hours?'hrs':'km';$('confirmTitle').textContent=hours?'As horas estão corretas?':'O KM está correto?';$('confirmPreviousLabel').textContent=hours?'Horas anteriores':'KM anterior';$('confirmNewLabel').textContent=hours?'Horas atualizadas':'KM atualizado';$('confirmVehicle').textContent=selected.identifier;$('confirmPrevious').textContent=`${fmt(selected.currentReading)} ${unit}`;$('confirmNew').textContent=`${fmt(pendingReading)} ${unit}`;$('confirmDifference').textContent=`+${fmt(difference)} ${unit}`;const unusual=difference>(hours?100:2000);$('confirmWarning').hidden=!unusual;$('confirmWarning').textContent=unusual?'A diferença está acima do normal. Confira o painel antes de confirmar.':'';dialog.showModal();};
  $('confirmForm').onsubmit=event=>{if(event.submitter?.value!=='confirm')return;const previous=selected.currentReading,hours=selected.unit==='h',unit=hours?'hrs':'km';selected.currentReading=pendingReading;selected.historyRecords=selected.historyRecords||[];selected.historyRecords.push({id:`driver-${Date.now()}`,date:new Date().toISOString().slice(0,10),type:'Leitura do motorista',service:hours?'Atualização de horas':'Atualização de KM',reading:pendingReading});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));form.hidden=true;$('successCard').hidden=false;$('successTitle').textContent=hours?'Horas atualizadas!':'KM atualizado!';$('successMessage').textContent=`${selected.identifier}: ${fmt(previous)} → ${fmt(pendingReading)} ${unit}.`;};
  $('newReadingBtn').onclick=()=>{form.reset();form.hidden=false;$('successCard').hidden=true;renderVehicle();scrollTo({top:0,behavior:'smooth'});};
  renderVehicle();
})();
